### ISSUE TITLE
Caddy configuration for telegram bot callback

### ISSUE THREAD

**Issue by claudioita** [korylprince/hassio-caddy#2]
Hi,
I have a HASSIO configuration, no SSL, and using your CADDY addon, everything works fine.

I added in the configuration this
   https://myname.duckdns.org {      
    tls /ssl/fullchain.pem /ssl/privkey.pem {                            
        alpn http/1.1                                                    
    }                                                                    
    proxy / 192.168.1.12:1880 {                                            
        transparent                                                      
        websocket                                                        
    }                                                                    
    log stdout                                                         
    errors stderr                                                      
}

What I am trying to do is connect my HASSIO/node-red to a telegram_bot. I can send messages from hassio/node-red to my telegram bot, just fine. Problem is the callback from telegram, I do receive this error

[warn] [telegrambot-switch:Telegram Switch] received callback in MY_CHAT_ID from 'TELEGRAM_USER' was unauthorized.

Maybe related to your addon?

**Comment by claudioita** [comment]
Tried to add this in the ini Caddy config file, but it gives error



   ipfilter / {
	rule allow
	ip 149.154.167.197/32
}

   ipfilter / {
	rule allow
	ip 149.154.167.198/31
}


   ipfilter / {
	rule allow
	ip 149.154.167.200/29
}

   ipfilter / {
	rule allow
	ip 149.154.167.208/28
}

   ipfilter / {
	rule allow
	ip 149.154.167.224/29
}

   ipfilter / {
	rule allow
	ip 149.154.167.232/31
}

**Comment by korylprince** [comment]
The ipfilter rule comes from a 3rd-party plugin that is not included in the addon (because it's not included in the Alpine Caddy package; only standard Caddy rules work.)

I'm not sure what is wrong with your Telegram bot, and I'm afraid I have no experience with that.

Judging from the error message, you have misconfigured something (not Caddy.)

I don't believe this is related to this addon, and I'm afraid I can't offer any further help, so I'm closing this issue. I suggest getting support from the author of whatever program gave you that log message.
